version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      codemirror:
        patterns: ['@codemirror/*', '@lezer/*', 'codemirror']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
