import { build } from 'esbuild';
import { mkdir, writeFile, readFile, copyFile, rm, rename } from 'node:fs/promises';
await mkdir('generated', { recursive: true });
const runtime = await build({ entryPoints: ['src/standalone.ts'], bundle: true, format: 'iife', minify: true, target: 'es2022', write: false });
await writeFile('generated/runtime.ts', `// Generated by scripts/build.mjs; do not edit.\nexport default ${JSON.stringify(runtime.outputFiles[0].text)};\n`);
const output = `.dist-next-${process.pid}`, previous = `.dist-previous-${process.pid}`;
await rm(output, { recursive: true, force: true }); await mkdir(output, { recursive: true });
try {
await build({ entryPoints: ['src/main.ts'], outdir: output, entryNames: 'app', chunkNames: 'chunks/[name]-[hash]', splitting: true, bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true, sourcemap: true, legalComments: 'linked' });
const revision = process.env.GITHUB_SHA || `local-${Date.now()}`;
const html = (await readFile('index.html', 'utf8'))
  .replace('</head>', `<meta name="scada-revision" content="${revision}"></head>`)
  .replace('src="./app.js"', `src="./app.js?v=${revision}"`)
  .replace('href="./app.css"', `href="./app.css?v=${revision}"`);
await writeFile(`${output}/index.html`, process.env.SCADA_DEV ? html.replace('</body>', '<script type="module" src="./dev-reload.js"></script></body>') : html);
await copyFile('public/favicon.svg', `${output}/favicon.svg`); await writeFile(`${output}/.nojekyll`, '');
await writeFile(`${output}/revision.json`, JSON.stringify({revision}));
if (process.env.SCADA_DEV) await writeFile(`${output}/dev-reload.js`, `const initial=document.querySelector('meta[name="scada-revision"]').content;setInterval(async()=>{try{const r=await fetch('./__dev/revision',{cache:'no-store'});if(r.ok&&(await r.json()).revision!==initial)location.reload();}catch{}},750);`);
await rm(previous, {recursive:true,force:true});
let hadPrevious = false;
try { await rename('dist', previous); hadPrevious = true; } catch (error) { if (error.code !== 'ENOENT') throw error; }
try { await rename(output, 'dist'); } catch (error) { if (hadPrevious) await rename(previous, 'dist'); throw error; }
await rm(previous, {recursive:true,force:true});
} finally { await rm(output, {recursive:true,force:true}); }
console.log('Built SCADA playground → dist/');
