import { build } from 'esbuild';
import { mkdir, writeFile, readFile, copyFile, rm } from 'node:fs/promises';
await mkdir('generated', { recursive: true });
const runtime = await build({ entryPoints: ['src/standalone.ts'], bundle: true, format: 'iife', minify: true, target: 'es2022', write: false });
await writeFile('generated/runtime.ts', `// Generated by scripts/build.mjs; do not edit.\nexport default ${JSON.stringify(runtime.outputFiles[0].text)};\n`);
await rm('dist', { recursive: true, force: true }); await mkdir('dist', { recursive: true });
await build({ entryPoints: ['src/main.ts'], outfile: 'dist/app.js', bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true, sourcemap: true, legalComments: 'linked' });
await copyFile('index.html', 'dist/index.html'); await copyFile('public/favicon.svg', 'dist/favicon.svg'); await writeFile('dist/.nojekyll', '');
console.log('Built SCADA playground → dist/');
